/// Dimension classifying recordable injuries by type.
table dim_injury_type
	lineageTag: b38cab1e-2920-4caf-b773-1134b0dc11e5

	/// ID of the injury
	column injury_type_ID
		dataType: string
		isHidden
		lineageTag: 639d7298-9f02-44f9-9efe-667d9e75e2aa
		summarizeBy: none
		sourceColumn: injury_type_ID

		annotation SummarizationSetBy = Automatic

	/// Namr of the injuiry
	column injury_type
		dataType: string
		lineageTag: 60a12b64-f73c-49c5-b354-f9d93d536bf5
		summarizeBy: none
		sourceColumn: injury_type
		sortByColumn: _order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column _order = right(dim_injury_type[injury_type_ID],1)
		isHidden
		lineageTag: 5f2d46eb-7e03-4ec4-ae17-49e7aa071a17
		summarizeBy: none

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column order
		dataType: string
		isHidden
		lineageTag: 04d69db3-bea0-4c62-b3b9-9e35e42936c2
		summarizeBy: none
		sourceColumn: order

		annotation SummarizationSetBy = Automatic

	column sdp_id
		dataType: string
		isHidden
		lineageTag: cd4176db-dca0-488e-859c-f223adaeb9a9
		summarizeBy: none
		sourceColumn: sdp_id

		annotation SummarizationSetBy = Automatic

	column sdp_group_name
		dataType: string
		isHidden
		lineageTag: 1d8b1f46-aa0a-47ab-b79e-d4d70e086304
		summarizeBy: none
		sourceColumn: sdp_group_name

		annotation SummarizationSetBy = Automatic

	column sdp_partition_col
		dataType: string
		isHidden
		lineageTag: cd24829d-25e4-4a56-b4c0-e9d4f1199b89
		summarizeBy: none
		sourceColumn: sdp_partition_col

		annotation SummarizationSetBy = Automatic

	column sdp_pipeline_run_id
		dataType: string
		isHidden
		lineageTag: 253ffc6d-0b7f-489c-a0d7-7a7ed7abf46d
		summarizeBy: none
		sourceColumn: sdp_pipeline_run_id

		annotation SummarizationSetBy = Automatic

	column sdp_group_filename
		dataType: string
		isHidden
		lineageTag: 668a3f16-491d-4c20-95f4-b09cac57ffce
		summarizeBy: none
		sourceColumn: sdp_group_filename

		annotation SummarizationSetBy = Automatic

	column sdp_load_date
		dataType: string
		isHidden
		lineageTag: 33939d5a-7f6d-4510-83b5-b4754ac4f8f0
		summarizeBy: none
		sourceColumn: sdp_load_date

		annotation SummarizationSetBy = Automatic

	column sdp_created_date
		dataType: string
		isHidden
		lineageTag: 0ed3ef27-3e2c-4eee-951e-6c9c54927802
		summarizeBy: none
		sourceColumn: sdp_created_date

		annotation SummarizationSetBy = Automatic

	column sdp_updated_date
		dataType: string
		isHidden
		lineageTag: 13788f46-48c8-42b9-b389-f2182199d26b
		summarizeBy: none
		sourceColumn: sdp_updated_date

		annotation SummarizationSetBy = Automatic

	column is_sdp_active
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 9b7397c6-e777-4480-be01-1c9a325c06cc
		summarizeBy: none
		sourceColumn: is_sdp_active

		annotation SummarizationSetBy = Automatic

	column sdp_effective_end_date
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 36ffcebc-dc86-4e02-9ce6-19e52a37d21e
		summarizeBy: none
		sourceColumn: sdp_effective_end_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition dim_injury_type = m
		mode: import
		queryGroup: 'Dimension & Reference Tables'
		source = ```
				let 
				    Source = Sql.Database(Global_Data_House_SQL, Globa_Data_House),
				    Load = Source{[Schema=Global_Dimensions_Schema, Item="dim_injury_type"]}[Data],
				    // Add Order column to maintain dimesional ordering in visuals
				    AddOrder = Table.AddColumn(
				        Load,
				        "order",
				        each Text.End([injury_type_ID], 1),
				        type text
				    ),
				    #"Filtered Rows" = Table.SelectRows(AddOrder, each [is_sdp_active] = true)
				in
				    #"Filtered Rows"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

