/// Free-text summary narratives provided by groups for monthly health and safety reporting.
table dim_freetext_summary
	lineageTag: f18cc940-bb03-4beb-8343-c2d9d1df0c9d

	/// Reporting year of the metrics.
	column reporting_year
		dataType: string
		lineageTag: 9d848ce7-2af3-44d5-ab3b-413d6bf4b5fe
		summarizeBy: none
		sourceColumn: reporting_year

		annotation SummarizationSetBy = Automatic

	/// Reporting month of the metrics.
	column reporting_month
		dataType: string
		lineageTag: 2273cef9-e737-4648-9630-40aca91a5672
		summarizeBy: none
		sourceColumn: reporting_month

		annotation SummarizationSetBy = Automatic

	/// ID representing the group.
	column group_id
		dataType: string
		isHidden
		lineageTag: bff278f9-2b07-4ba8-a915-8d797bad11f2
		summarizeBy: none
		sourceColumn: group_id

		annotation SummarizationSetBy = Automatic

	/// Free-text summary narrative provided by the group.
	column free_text
		dataType: string
		lineageTag: f7287ec8-55de-466e-8933-56ee4f6a48a1
		summarizeBy: none
		sourceColumn: free_text

		annotation SummarizationSetBy = Automatic

	/// Name of the report associated with the free-text summary.
	column report_name
		dataType: string
		lineageTag: 4a77975b-1d5e-4682-9a0b-b4325d923d46
		summarizeBy: none
		sourceColumn: report_name

		annotation SummarizationSetBy = Automatic

	column sdp_id
		dataType: string
		isHidden
		lineageTag: e0a15edd-5060-4c83-b223-56a6ecf6296c
		summarizeBy: none
		sourceColumn: sdp_id

		annotation SummarizationSetBy = Automatic

	column sdp_group_name
		dataType: string
		isHidden
		lineageTag: ab371e98-73ff-4868-aef1-fc6b236a3b2c
		summarizeBy: none
		sourceColumn: sdp_group_name

		annotation SummarizationSetBy = Automatic

	column sdp_partition_col
		dataType: string
		isHidden
		lineageTag: 666f7ca4-0ed4-4243-b390-699139ec9766
		summarizeBy: none
		sourceColumn: sdp_partition_col

		annotation SummarizationSetBy = Automatic

	column sdp_pipeline_run_id
		dataType: string
		isHidden
		lineageTag: 89d429bd-5b2c-4c95-b889-8c87178236df
		summarizeBy: none
		sourceColumn: sdp_pipeline_run_id

		annotation SummarizationSetBy = Automatic

	column sdp_group_filename
		dataType: string
		isHidden
		lineageTag: b5a581e7-6c46-4e46-a12d-e71886317037
		summarizeBy: none
		sourceColumn: sdp_group_filename

		annotation SummarizationSetBy = Automatic

	column sdp_load_date
		dataType: string
		isHidden
		lineageTag: b2d66891-f91c-41f5-a0b1-899630a4ead6
		summarizeBy: none
		sourceColumn: sdp_load_date

		annotation SummarizationSetBy = Automatic

	column sdp_created_date
		dataType: string
		isHidden
		lineageTag: 08c9d866-9630-4fb2-8692-bc076c373cca
		summarizeBy: none
		sourceColumn: sdp_created_date

		annotation SummarizationSetBy = Automatic

	column sdp_updated_date
		dataType: string
		isHidden
		lineageTag: 91bf8b06-0844-41f9-8724-90237dcff712
		summarizeBy: none
		sourceColumn: sdp_updated_date

		annotation SummarizationSetBy = Automatic

	column end_of_month = EOMONTH(date('dim_freetext_summary'[Reporting_year],dim_freetext_summary[Reporting_month],1),0)
		formatString: General Date
		lineageTag: d89f2f84-eecf-4770-8d4d-b66695424181
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column is_sdp_active
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 85fc2a65-932b-4623-9e59-014d8078f853
		summarizeBy: none
		sourceColumn: is_sdp_active

		annotation SummarizationSetBy = Automatic

	column sdp_effective_end_date
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 028b851d-be0a-439e-a7f2-c0a1546e3a2b
		summarizeBy: none
		sourceColumn: sdp_effective_end_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column year_month = FORMAT(date('dim_freetext_summary'[reporting_year],dim_freetext_summary[Reporting_month],1),"YYYY-MM")
		lineageTag: eb765622-9c63-4394-b6c9-eed99cb2986c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition dim_freetext_summary = m
		mode: import
		queryGroup: 'Dimension & Reference Tables'
		source =
				let
				    Source = Sql.Database(Global_Data_House_SQL, Globa_Data_House),
				    Load = Source{[Schema=Global_Dimensions_Text_Summary,Item="dim_summary_notes"]}[Data],
				    #"Filtered Rows on HS" = Table.SelectRows(Load, each true),
				    #"Filtered Rows" = Table.SelectRows(#"Filtered Rows on HS", each [is_sdp_active] = true)
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

